# Generated by Django 5.1.8 on 2026-06-22 11:51

import json
from decimal import Decimal

from django.utils.dateparse import parse_date, parse_datetime
from django.db import migrations, models


COMPANY_PAYMENT_ARCHIVE_MARKER = "\n__company_monthly_payment_duplicate_archive__="


def remove_user_payment_permissions(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')

    user_content_type = ContentType.objects.filter(app_label='payroll', model='user').first()
    if not user_content_type:
        return

    Permission.objects.filter(
        content_type=user_content_type,
        codename__in=['approve_payment', 'process_salary'],
    ).delete()


def restore_user_payment_permissions(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')

    user_content_type = ContentType.objects.filter(app_label='payroll', model='user').first()
    if not user_content_type:
        return

    for codename, name in [
        ('approve_payment', 'Can approve payment'),
        ('process_salary', 'Can process salary'),
    ]:
        Permission.objects.get_or_create(
            content_type=user_content_type,
            codename=codename,
            defaults={'name': name},
        )


def normalize_payment_partial_amounts(apps, schema_editor):
    Payment = apps.get_model('payroll', 'Payment')

    Payment.objects.filter(
        is_partial=True,
        amount_paid__isnull=True,
        net_amount__gt=0,
    ).update(amount_paid=Decimal('0'))

    Payment.objects.filter(
        is_partial=True,
        amount_paid__isnull=True,
        net_amount=0,
    ).update(is_partial=False)

    Payment.objects.filter(
        is_partial=True,
        amount_paid__gte=models.F('net_amount'),
    ).update(is_partial=False, remaining_balance=Decimal('0'))

    Payment.objects.filter(
        is_partial=False,
        amount_paid__isnull=False,
        amount_paid__lt=models.F('net_amount'),
    ).update(amount_paid=models.F('net_amount'), remaining_balance=Decimal('0'))


def _serialize_company_payment(row):
    return {
        'id': str(row.id),
        'company_id': str(row.company_id),
        'payment_month': row.payment_month,
        'amount_due': str(row.amount_due),
        'amount_paid': str(row.amount_paid),
        'status': row.status,
        'payment_date': row.payment_date.isoformat() if row.payment_date else None,
        'notes': row.notes,
        'created_at': row.created_at.isoformat() if row.created_at else None,
        'updated_at': row.updated_at.isoformat() if row.updated_at else None,
    }


def _payment_status(amount_due, amount_paid):
    if amount_paid >= amount_due and amount_due > 0:
        return 'paid'
    if amount_paid > 0:
        return 'partial'
    return 'unpaid'


def resolve_company_month_duplicates(apps, schema_editor):
    CompanyMonthlyPayment = apps.get_model('payroll', 'CompanyMonthlyPayment')

    duplicates = (
        CompanyMonthlyPayment.objects
        .values('company_id', 'payment_month')
        .annotate(row_count=models.Count('id'))
        .filter(row_count__gt=1)
    )

    for duplicate in duplicates:
        rows = list(
            CompanyMonthlyPayment.objects
            .filter(
                company_id=duplicate['company_id'],
                payment_month=duplicate['payment_month'],
            )
            .order_by('created_at', 'id')
        )
        keeper = rows[0]
        removed_rows = rows[1:]
        archive = {
            'keeper': _serialize_company_payment(keeper),
            'duplicates': [_serialize_company_payment(row) for row in removed_rows],
        }

        amount_due = max((row.amount_due or Decimal('0') for row in rows), default=Decimal('0'))
        amount_paid = sum((row.amount_paid or Decimal('0') for row in rows), Decimal('0'))
        payment_dates = [row.payment_date for row in rows if row.payment_date]

        keeper.amount_due = amount_due
        keeper.amount_paid = amount_paid
        keeper.status = _payment_status(amount_due, amount_paid)
        keeper.payment_date = max(payment_dates) if payment_dates else None
        keeper.notes = f"{keeper.notes or ''}{COMPANY_PAYMENT_ARCHIVE_MARKER}{json.dumps(archive, sort_keys=True)}"
        keeper.save(update_fields=['amount_due', 'amount_paid', 'status', 'payment_date', 'notes', 'updated_at'])

        CompanyMonthlyPayment.objects.filter(id__in=[row.id for row in removed_rows]).delete()


def restore_company_month_duplicates(apps, schema_editor):
    CompanyMonthlyPayment = apps.get_model('payroll', 'CompanyMonthlyPayment')

    archived_rows = CompanyMonthlyPayment.objects.filter(notes__contains=COMPANY_PAYMENT_ARCHIVE_MARKER)
    for keeper in archived_rows:
        notes, payload = keeper.notes.rsplit(COMPANY_PAYMENT_ARCHIVE_MARKER, 1)
        archive = json.loads(payload)
        original_keeper = archive['keeper']

        keeper.amount_due = Decimal(original_keeper['amount_due'])
        keeper.amount_paid = Decimal(original_keeper['amount_paid'])
        keeper.status = original_keeper['status']
        keeper.payment_date = parse_date(original_keeper['payment_date']) if original_keeper['payment_date'] else None
        keeper.notes = original_keeper['notes']
        keeper.save(update_fields=['amount_due', 'amount_paid', 'status', 'payment_date', 'notes', 'updated_at'])

        for row in archive['duplicates']:
            if CompanyMonthlyPayment.objects.filter(id=row['id']).exists():
                continue
            created = CompanyMonthlyPayment.objects.create(
                id=row['id'],
                company_id=row['company_id'],
                payment_month=row['payment_month'],
                amount_due=Decimal(row['amount_due']),
                amount_paid=Decimal(row['amount_paid']),
                status=row['status'],
                payment_date=parse_date(row['payment_date']) if row['payment_date'] else None,
                notes=row['notes'],
            )
            CompanyMonthlyPayment.objects.filter(id=created.id).update(
                created_at=parse_datetime(row['created_at']) if row['created_at'] else created.created_at,
                updated_at=parse_datetime(row['updated_at']) if row['updated_at'] else created.updated_at,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RunPython(remove_user_payment_permissions, restore_user_payment_permissions),
        migrations.RemoveConstraint(
            model_name='payment',
            name='partial_payment_consistency',
        ),
        migrations.RunPython(normalize_payment_partial_amounts, migrations.RunPython.noop),
        migrations.RunPython(resolve_company_month_duplicates, restore_company_month_duplicates),
        migrations.AddConstraint(
            model_name='companymonthlypayment',
            constraint=models.UniqueConstraint(fields=('company', 'payment_month'), name='unique_company_payment_per_month'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(
                condition=(
                    (
                        models.Q(is_partial=True) &
                        models.Q(amount_paid__isnull=False) &
                        models.Q(amount_paid__lt=models.F('net_amount'))
                    ) |
                    (
                        models.Q(is_partial=False) &
                        (
                            models.Q(amount_paid__isnull=True) |
                            models.Q(amount_paid__gte=models.F('net_amount'))
                        )
                    )
                ),
                name='partial_payment_consistency'
            ),
        ),
    ]
