# Generated by Django 5.1.8 on 2026-06-28 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_repair_render_schema_drift'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deduction',
            name='deduction_status_valid',
        ),
        migrations.AddField(
            model_name='deduction',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount already recovered through payroll', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='deduction',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Outstanding deduction balance', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='deduction',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldeduction',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount already recovered through payroll', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='historicaldeduction',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Outstanding deduction balance', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='historicaldeduction',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('settled', 'Settled'), ('applied', 'Applied'), ('cancelled', 'Cancelled'), ('terminated', 'Terminated'), ('pending_hr', 'Pending HR Approval')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldeduction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('settled', 'Settled'), ('applied', 'Applied'), ('cancelled', 'Cancelled'), ('terminated', 'Terminated'), ('pending_hr', 'Pending HR Approval')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='deduction',
            constraint=models.CheckConstraint(check=models.Q(('amount_paid__gte', 0)), name='deduction_amount_paid_positive'),
        ),
        migrations.AddConstraint(
            model_name='deduction',
            constraint=models.CheckConstraint(check=models.Q(('remaining_balance__gte', 0)), name='deduction_remaining_balance_positive'),
        ),
        migrations.AddConstraint(
            model_name='deduction',
            constraint=models.CheckConstraint(check=models.Q(('amount_paid__lte', models.F('amount'))), name='deduction_amount_paid_not_over_amount'),
        ),
        migrations.AddConstraint(
            model_name='deduction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'pending'), ('status', 'partial'), ('status', 'settled'), ('status', 'applied'), ('status', 'cancelled'), ('status', 'terminated'), ('status', 'pending_hr'), _connector='OR')), name='deduction_status_valid'),
        ),
    ]
