# Generated by BlackboxAI to add missing Paystack "last_*" columns safely.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0005_add_failure_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="paystack_last_status",
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="paystack_last_response",
            field=models.JSONField(blank=True, null=True),
        ),
    ]

