# Generated by Django 5.1.8 on 2026-07-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_add_paystack_last_status_and_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='paystack_last_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='paystack_last_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
