# Generated by Django 4.2.7 on 2026-05-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_attendance_clock_method_attendance_leave_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_month',
            field=models.CharField(blank=True, help_text='Format: YYYY-MM', max_length=7, null=True),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('employee', 'payment_month'), name='unique_payment_per_employee_per_month'),
        ),
    ]
