# Generated by Django 4.2.7 on 2026-05-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_payment_payment_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='contact_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='company',
            name='termination_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('terminated', 'Not Active')], default='active', max_length=15),
        ),
    ]
