# Generated by Django 4.2.7 on 2026-05-08 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_rename_contact_email_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_request_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmployeeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('salary_advance', 'Salary Advance'), ('loan', 'Loan'), ('company_expense', 'Company Expense'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('proof_photo', models.ImageField(blank=True, null=True, upload_to='requests/proof/%Y/%m/')),
                ('receipt_file', models.ImageField(blank=True, null=True, upload_to='requests/receipts/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='payroll.employee')),
            ],
            options={
                'db_table': 'employee_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
