# Generated by Django 5.2.14 on 2026-05-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_user_is_request_admin_employeerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_self_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_partial',
            field=models.BooleanField(default=False),
        ),
    ]
