# Generated by Django 5.2.14 on 2026-05-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_payment_to_guards',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
