# Generated by Django 5.2.14 on 2026-05-10 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_alter_company_profit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='requests/attachments/%Y/%m/')),
                ('file_type', models.CharField(choices=[('proof', 'Proof'), ('receipt', 'Receipt')], max_length=10)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='payroll.employeerequest')),
            ],
            options={
                'db_table': 'employee_request_attachments',
            },
        ),
    ]
