# Generated by Django 5.2.14 on 2026-05-18 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_exporttoken_is_2fa_verified_exporttoken_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paystack_transfer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'OTP must be a 6-digit number.')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('pending_paystack_otp', 'Awaiting Paystack OTP')], default='pending', max_length=25),
        ),
    ]
