# Generated by Django 5.2.14 on 2026-05-18 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_payment_paystack_transfer_code_alter_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='hr_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deduction',
            name='hr_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approved_deductions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='hr_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='hr_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_approved_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_hr_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('cancelled', 'Cancelled'), ('terminated', 'Terminated'), ('pending_hr', 'Pending HR Approval')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('pending_paystack_otp', 'Awaiting Paystack OTP'), ('pending_hr', 'Pending HR Approval')], default='pending', max_length=25),
        ),
    ]
