# Generated by Django 5.2.14 on 2026-05-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_deduction_hr_approved_deduction_hr_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='reference',
            field=models.CharField(max_length=100),
        ),
    ]
